fruit = []
f1 = input("Enter fruit 1: ")
fruit.append(f1)
f2 = input("Enter fruit 2: ")       
fruit.append(f2)
f3 = input("Enter fruit 3: ")           
fruit.append(f3)
f4 = input("Enter fruit 4: ")           
fruit.append(f4)    
f5 = input("Enter fruit 5: ")           
fruit.append(f5)        
f6 = input("Enter fruit 6: ")           
fruit.append(f6)        
f7 = input("Enter fruit 7: ")           
fruit.append(f7)            
print(fruit)